### ISSUE TITLE
Problem Statement of Image Feature Detection 

### ISSUE THREAD

**Issue by Zhou4truth** [Zhou4truth/imageFeatureDetection#2]
Hi Professor, 
   Here is my Problem Statement for Image Feature Detection. I am very sorry for the late submission of this assignment. I mistakenly thought this is the SRS assignment. Thank you for your patience and kind understanding.
 Best regards,
Gaofeng
[Problem_Statement.pdf](https://github.com/Zhou4truth/imageFeatureDetection/files/14044369/Problem_Statement.pdf)

**Comment by smiths** [comment]
Feedback:

- try shorter sentences.  Some of the given sentences have too much going on for the reader to easily comprehend what you are saying
- the problem statement is more about the interface for the software than what the software does
- the main goal should be a functional goal - what is the software going to calculate?  The registration information, the features of the image are mentioned in the problem, but they should be explicitly part of the goal
- the goals should be listed as separate bullets, rather than discussed in a paragraph
- the stakeholders should be the typical people that will use your software
- the hardware shouldn't just be your hardware, but the generic operating environment in which your software will function.  Hopefully your software can work for both Windows and Mac.
- you don't specify the software to be used for development at this stage; that is a design decision for later
- provide pointers to similar software
- provide citations

The project fits well with CAS 741, so I will approve it.  You don't need to modify the problem statement at this time, but you might find it helpful to do so.  The requirements document should take into account the feedback I gave above.  In particular, our first priority is to express the theoretical model.  The second priority in the documentation is nonfunctional requirements about usability.  (The nonfunctional requirements are very important, but the emphasis in the SRS is on the theory and calculations.)

**Comment by Zhou4truth** [comment]
Thank you, Professor. I will correct my Problem Statement later and  integrate your valuable advice into my SRS documentation.
